parameters:
    selltag_nacex.nacex_client.class: Selltag\NacexBundle\Services\NacexClient

services:
    selltag_nacex.nacex_client:
        class: %selltag_nacex.nacex_client.class%
        arguments:
            - %selltag_nacex.nacex_username%
            - %selltag_nacex.nacex_password%
            - %selltag_nacex.nacex_url%
