parameters:
    selltag_nacex.nacex_client.class: Selltag\NacexBundle\Services\NacexClientService

services:
    selltag_nacex.nacex_client:
        class: %selltag_nacex.nacex_client.class%
        arguments:
            - %nacex_username%
            - %nacex_password%
            - %nacex_url%
